{% set name = "palmari" %}
{% set version = "0.2.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/palmari-{{ version }}.tar.gz
  sha256: 168d09fc3ba471a87f4f32ea4952c2869bf0a1a48306f25e8076ce8196379304

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - dask-core >=2022.1.0
    - dask-image >=2021.12.0
    - imageio-ffmpeg
    - magicgui >=0.5.0
    - matplotlib-base >=3.5
    - munkres
    - napari
    - napari-aicsimageio
    - numpy
    - pandas
    - python >=3.8
    - pyyaml
    - qtpy
    - scikit-image >=0.18.3
    - scikit-learn
    - toml
    - tqdm
    - trackpy >=0.5.0

test:
  imports:
    - palmari
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://github.com/hippover/palmari
  summary: A pipeline for PALM movies analysis (pre-processing, localization, drifft correction, tracking)
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hippover
    - jaimergp
